---
title: "Introduction to R - Preliminary Instructions"
author: "Viviane Schuch - vschuch@msm.edu - Johnson's Lab -  Morehouse School of Medicine"
date: 'Compiled: `r Sys.Date()`'
output:
  html_document:
    df_print: paged
  html_notebook: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to R – preliminary instructions

### Supplementary Reading Material  
**R for Applied Epidemiology and Public Health:** https://epirhandbook.com/r-basics.html

We strongly recommend the study of the tutorial below for better use of the course:

**DataCamp - Free introduction to R:** https://www.datacamp.com/courses/free-introduction-to-r

**This tutorial available on-line:** https://vivischuch.github.io/MSM_Rclass/Hands_on.html


# Install R and RStudio 
**What is R**: R is a free statistical computing and graphing software that can be downloaded and distributed free of charge under the GNU license.

**What is RStudio**: The RStudio is a set of integrated tools designed to help you be more productive with R. Both run on Windows, Linux, and macOS. 

Alternatively, you can use **RStudio Cloud**, which has functions and looks the same as the RStudio you can install on your computer. Below we list all installation options:

## Windows Users 
### To Install R 
1. To download R for Windows, go to the R website www.r-project.org 
2. Click on CRAN (Comprehensive R Archive Network) 
3. Choose the mirror of your choice (CRAN mirrors)
4. Click on Windows 95 or later 
5. Click base and save the R for Windows file. Then just run the file. 

### To Install RStudio 
1. Go to https://www.rstudio.com/products/rstudio/download/preview/ 
2. Under Desktop Version - Installers, click on Windows 7+ 
3. Follow the installation steps. 

##  Mac Users 
### To Install R 
1. Open an internet browser and go to www.r-project.org. 
2. Click the "download R" link in the middle of the page under "Getting Started." 
3. Select a CRAN location (a mirror site) and click the corresponding link. 
4. Click on the "Download R for (Mac) OS X" link at the top of the page. 
5. Click on the file containing the latest version of R under "Files." 
6. Save the .pkg file, double-click it to open it, and follow the installation instructions. 
7. Now that R is installed, you must download and install RStudio. 

### To Install RStudio 
1. Go to https://www.rstudio.com/products/rstudio/download/preview/ 
2. Click on "Download RStudio Desktop." 
3. Click on the version recommended for your system, or the latest Mac version, save the .dmg file on your computer, double-click it to open, and then drag and drop it to your applications folder. 


## RStudio Cloud Users
1. Start RStudio Cloud: https://rstudio.cloud/ 
2. Click on: **Your Workspace** then click on the: **New Project** box. 
3. Click on the “**Untitled Project**” text in the upper left and type a name (Data-Science) for your project.  


# RStudio orientation

### First, open Rstudio.
As their icons can look very similar, be sure you are opening Rstudio and not R. For RStudio to work you must also have R installed on the computer. 
Rstudio is a Graphical User Interface (GUI) for easier use of R. 

### By default RStudio displays four rectangle panes.

If your RStudio displays only one left pane it is because you have no scripts open yet. 

**The Source Pane**: This pane, by default in the upper-left, is a space to edit, run, and save your scripts. Scripts contain the commands you want to run. This pane can also display datasets (data frames) for viewing. 

**The R Console Pane**: The R Console, by default the left or lower-left pane in RStudio, is the home of the R “engine”. This is where the commands are actually run and non-graphic outputs and error/warning messages appear. You can directly enter and run commands in the R Console, but realize that these commands are not saved as they are when running commands from a script. 

**The Environment Pane**: This pane, by default in the upper-right, is most often used to see brief summaries of objects in the R Environment in the current session. These objects could include imported, modified, or created datasets, parameters you have defined (e.g. a specific epi week for the analysis), or vectors or lists you have defined during analysis (e.g. names of regions). You can click on the arrow next to a data frame name to see its variables.  This pane also contains History where can see commands that you can previously. It also has a “Tutorial” tab where you can complete interactive R tutorials if you have the learnr package installed. It also has a “Connections” pane for external connections, and can have a “Git” pane if you choose to interface with Github. 

**Plots, Viewer, Packages, and Help Pane**: The lower-right pane includes several important tabs. Typical plot graphics including maps will display in the Plot pane. Interactive or HTML outputs will display in the Viewer pane. The Help pane can display documentation and help files. The Files pane is a browser which can be used to open or delete files. The Packages pane allows you to see, install, update, delete, load/unload R packages, and see which version of the package you have. 

# Key terms

**Objects** - Everything you store in R - datasets, variables, a list, a total number, even outputs such as graphs - are objects which are assigned a name and can be referenced in later commands.  

**Data Types** - R has a wide variety of data types including scalars, vectors (numerical, character, logical), matrices, data frames, and lists. 

**Vector** – A collection of ordered homogeneous elements. We can think of matrices, arrays, lists and data frames as deviations from a vector. The deviations are related to the two characteristics: order and homogeneity. 

**Matrix** - A vector with two-dimensional shape information. All columns in a matrix must have the same mode (numeric, character, etc.) and the same length. Also, matrices can have row and column names, which can be determined and/or assigned by rownames and colnames.  

**Array** - Arrays are similar to matrices but can have more than two dimensions.  

**List** - A vector with possible heterogeneous elements. The elements of a list can be numeric vectors, character vectors, matrices, arrays, and lists. You create a list by using the list() command. 

**Data Frames** - A list with possible heterogeneous vector elements of the same length. The elements of a data frame in that different columns can have different modes (numeric, character, factor, etc.), but they must all be of the same length. 

**Functions** - A function is a code operation that accept inputs and returns a transformed output.  

**Packages** - An R package is a shareable bundle of functions.  

**Scripts** - A script is the document file that hold your commands.

